#!/sbin/busybox sh

export BOOTREC_EVENT_NODE="/dev/input/event5 c 13 69"
export BOOTREC_EVENT="/dev/input/event5"
export BOOTREC_LED_RED="/sys/class/leds/lm3533-red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/lm3533-green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/lm3533-blue/brightness"
